# sqlite (default setup).

development:
  adapter: sqlite3
  database: db/development.db
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.db
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/production.db
  pool: 5
  timeout: 5000
